### PR TITLE
fix: capture redirected requests in waterfall

### LINKED ISSUE #175: Redirects and DNS failures not represented correctly
The waterfall chart is not showing **redirects** or **DNS failure** requests correctly.  These are implemented differently within the Chrome events, so likely that we are not extracting these requests correctly for storing into ES for displaying on the waterfall chart.

Issues:
* DNS failures
  * There is a row in the waterfall chart for the domain/request, but no chart data showing the DNS lookup time (which happens to fail)
* Redirects are not shown at all
  * There is no row in the waterfall chart

image

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #175 
+ Redirected requests have the same `requestId` which was overriding the original request with the redirected request. As a result the redirected requests was simply not shown in the waterfall. 
+ The solution is to check if the request is issued with the same `requestId` and simply mimic the usual flow from `requestSent` -> `responseReceived` -> `LoadingFinished` by using the redirected response which is available as part of the `event.redirectedResponse` data. 

Check the below events for a sample website which goes from HTTP -> HTTPS and how 301 works. 
```json
{"type":"journey/network_info","@timestamp":1609895099415610.8,"journey":{"name":"check that title is present","id":"check that title is present"},"step":{"name":"go to app","index":1},"payload":{"step":{"name":"go to app","index":1},"timestamp":1609895099415610.8,"url":"http://vigneshh.in/","request":{"url":"http://vigneshh.in/","method":"GET","headers":{"upgrade_insecure_requests":"1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.0 Safari/537.36","host":"vigneshh.in","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept_encoding":"gzip, deflate","accept_language":"en-GB,en;q=0.9"},"mixed_content_type":"none","initial_priority":"VeryHigh","referrer_policy":"strict-origin-when-cross-origin"},"type":"Document","method":"GET","request_sent_time":1012040.277427,"is_navigation_request":true,"status":301,"load_end_time":1012040.365573,"response_received_time":1012040.365573,"response":{"url":"http://vigneshh.in/","status":301,"status_text":"Moved Permanently","headers":{"date":"Wed, 06 Jan 2021 01:04:59 GMT","transfer_encoding":"chunked","connection":"keep-alive","cache_control":"max-age=3600","expires":"Wed, 06 Jan 2021 02:04:59 GMT","location":"https://vigneshh.in/","cf_request_id":"0776d2d4760000f55947917000000001","report_to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report?s=ETVgpWk5MwNmSv7ZSCQ%2B%2F5mWTTcwMGltJh0waEBoj%2FNrzwHHHikgeL5fas7I5zXcmBhvy7DOshY0K%2B7XUlaGOjpzM80ZK6s0AHCB1ptbObHBLe%2FGsWFNgQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","nel":"{\"report_to\":\"cf-nel\",\"max_age\":604800}","vary":"Accept-Encoding","x_content_type_options":"nosniff","server":"cloudflare","cf_ray":"60d18733f9e9f559-SEA"},"headers_text":"HTTP/1.1 301 Moved Permanently\r\nDate: Wed, 06 Jan 2021 01:04:59 GMT\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nCache-Control: max-age=3600\r\nExpires: Wed, 06 Jan 2021 02:04:59 GMT\r\nLocation: https://vigneshh.in/\r\ncf-request-id: 0776d2d4760000f55947917000000001\r\nReport-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report?s=ETVgpWk5MwNmSv7ZSCQ%2B%2F5mWTTcwMGltJh0waEBoj%2FNrzwHHHikgeL5fas7I5zXcmBhvy7DOshY0K%2B7XUlaGOjpzM80ZK6s0AHCB1ptbObHBLe%2FGsWFNgQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\nNEL: {\"report_to\":\"cf-nel\",\"max_age\":604800}\r\nVary: Accept-Encoding\r\nX-Content-Type-Options: nosniff\r\nServer: cloudflare\r\nCF-RAY: 60d18733f9e9f559-SEA\r\n\r\n","mime_type":"","request_headers":{"host":"vigneshh.in","connection":"keep-alive","upgrade_insecure_requests":"1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept_encoding":"gzip, deflate","accept_language":"en-GB,en;q=0.9"},"request_headers_text":"GET / HTTP/1.1\r\nHost: vigneshh.in\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-GB,en;q=0.9\r\n","connection_reused":false,"connection_id":52,"remote_i_p_address":"[2606:4700:3030::681c:133e]","remote_port":80,"from_disk_cache":false,"from_service_worker":false,"from_prefetch_cache":false,"encoded_data_length":673,"timing":{"request_time":1012040.278533,"proxy_start":-1,"proxy_end":-1,"dns_start":0.347,"dns_end":35.274,"connect_start":35.274,"connect_end":50.998,"ssl_start":-1,"ssl_end":-1,"worker_start":-1,"worker_ready":-1,"worker_fetch_start":-1,"worker_respond_with_settled":-1,"send_start":51.102,"send_end":51.187,"push_start":0,"push_end":0,"receive_headers_end":85.369},"response_time":1609895099499.776,"protocol":"http/1.1","security_state":"insecure"},"timings":{"blocked":0.3469999646767974,"queueing":1.1060000397264957,"proxy":-1,"dns":34.92700005881488,"ssl":-1,"connect":15.72399993892759,"send":0.0849999487400055,"wait":34.18199997395277,"receive":1.6710000345483422,"total":88.14600005280226}},"package_version":"0.0.1-alpha.8"}

{"type":"journey/network_info","@timestamp":1609895099505859,"journey":{"name":"check that title is present","id":"check that title is present"},"step":{"name":"go to app","index":1},"payload":{"step":{"name":"go to app","index":1},"timestamp":1609895099505859,"url":"https://vigneshh.in/","request":{"url":"https://vigneshh.in/","method":"GET","headers":{"upgrade_insecure_requests":"1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.0 Safari/537.36","method":"GET","authority":"vigneshh.in","scheme":"https","path":"/","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec_fetch_site":"none","sec_fetch_mode":"navigate","sec_fetch_user":"?1","sec_fetch_dest":"document","sec_ch_ua":"\";Not\\\\A\\\"Brand\";v=\"99\", \"Chromium\";v=\"88\"","sec_ch_ua_mobile":"?0","accept_encoding":"gzip, deflate, br","accept_language":"en-GB,en;q=0.9"},"mixed_content_type":"none","initial_priority":"VeryHigh","referrer_policy":"strict-origin-when-cross-origin"},"type":"Document","method":"GET","request_sent_time":1012040.365573,"is_navigation_request":true,"status":200,"load_end_time":1012040.564763,"response_received_time":1012040.567352,"response":{"url":"https://vigneshh.in/","status":200,"status_text":"","headers":{"date":"Wed, 06 Jan 2021 01:04:59 GMT","content_type":"text/html; charset=utf-8","set_cookie":"__cfduid=df3f740b1d7c6b826023178e9eb075e731609895099; expires=Fri, 05-Feb-21 01:04:59 GMT; path=/; domain=.vigneshh.in; HttpOnly; SameSite=Lax","last_modified":"Wed, 17 Jun 2020 21:25:03 GMT","access_control_allow_origin":"*","expires":"Tue, 05 Jan 2021 23:33:29 GMT","cache_control":"max-age=600","x_proxy_cache":"MISS","x_github_request_id":"3A50:9DDA:1D63276:217135C:5FF4F4F0","via":"1.1 varnish","age":"0","x_served_by":"cache-sea4480-SEA","x_cache":"HIT","x_cache_hits":"1","x_timer":"S1609895100.637506,VS0,VE77","vary":"Accept-Encoding","x_fastly_request_id":"530154c96c465eb52b011e3840dd4abdbe458cec","cf_cache_status":"DYNAMIC","cf_request_id":"0776d2d4ec0000f595ecb0c000000001","expect_ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","report_to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report?s=iGmKNu4iAQOZ%2BSHSlaXGYbHoyQpRBfjQPT91NCwk75y%2B1K%2BoOVynIlQJJkh0UfWhCLB0Had1oyismCAri9wwwJEsteUB79Bc%2Bw%2BZfTREevWB0eJYvA5yvQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","nel":"{\"report_to\":\"cf-nel\",\"max_age\":604800}","strict_transport_security":"max-age=2592000; includeSubDomains","x_content_type_options":"nosniff","server":"cloudflare","cf_ray":"60d18734aee8f595-SEA","content_encoding":"br"},"mime_type":"text/html","request_headers":{"method":"GET","authority":"vigneshh.in","scheme":"https","path":"/","upgrade_insecure_requests":"1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec_fetch_site":"none","sec_fetch_mode":"navigate","sec_fetch_user":"?1","sec_fetch_dest":"document","sec_ch_ua":"\";Not\\\\A\\\"Brand\";v=\"99\", \"Chromium\";v=\"88\"","sec_ch_ua_mobile":"?0","accept_encoding":"gzip, deflate, br","accept_language":"en-GB,en;q=0.9"},"connection_reused":false,"connection_id":62,"remote_i_p_address":"[2606:4700:3030::681c:133e]","remote_port":443,"from_disk_cache":false,"from_service_worker":false,"from_prefetch_cache":false,"encoded_data_length":3332,"timing":{"request_time":1012040.367565,"proxy_start":-1,"proxy_end":-1,"dns_start":0.242,"dns_end":36.614,"connect_start":36.614,"connect_end":80.609,"ssl_start":52.111,"ssl_end":80.6,"worker_start":-1,"worker_ready":-1,"worker_fetch_start":-1,"worker_respond_with_settled":-1,"send_start":80.808,"send_end":80.991,"push_start":0,"push_end":0,"receive_headers_end":195.368},"response_time":1609895099698.864,"protocol":"h2","security_state":"secure","security_details":{"protocol":"TLS 1.3","key_exchange":"","key_exchange_group":"X25519","cipher":"AES_128_GCM","certificate_id":0,"subject_name":"sni.cloudflaressl.com","san_list":["sni.cloudflaressl.com","*.vigneshh.in","vigneshh.in"],"issuer":"Cloudflare Inc ECC CA-3","valid_from":1595980800,"valid_to":1627560000,"signed_certificate_timestamp_list":[],"certificate_transparency_compliance":"unknown"}},"timings":{"blocked":0.24199998006224632,"queueing":1.9919999176636338,"proxy":-1,"dns":36.37200000230223,"ssl":28.488999931141734,"connect":43.99500007275492,"send":0.1829999964684248,"wait":114.37699990347028,"receive":1.8300000810995698,"total":199.1899999557063}},"package_version":"0.0.1-alpha.8"}
```

### Verification

Timings for `http://vigneshh.in` -> NO SSL timing as its HTTP endpoint

```json
{
  "blocked": 0.3469999646767974,
  "queueing": 1.1060000397264957,
  "proxy": -1,
  "dns": 34.92700005881488,
  "ssl": -1,
  "connect": 15.72399993892759,
  "send": 0.0849999487400055,
  "wait": 34.18199997395277,
  "receive": 1.6710000345483422,
  "total": 88.14600005280226
}
```
Timings for `https://vigneshh.in` 

```json
{
  "blocked": 0.24199998006224632,
  "queueing": 1.9919999176636338,
  "proxy": -1,
  "dns": 36.37200000230223,
  "ssl": 28.488999931141734,
  "connect": 43.99500007275492,
  "send": 0.1829999964684248,
  "wait": 114.37699990347028,
  "receive": 1.8300000810995698,
  "total": 199.1899999557063
}
```

### CODE REVIEW

File: src/plugins/network.ts [hunk 1]
```diff
@@ -51,6 +51,41 @@ export class NetworkManager {
...
+         * Edge case, we handle it to proceed with next navigation
+         */
+        this._onLoadingFailed(
+          Object.assign(event, {
+            type: event.type,
+            errorText: 'redirectResponse data is not available',
+          })
+        );
+      }
+      const redirectedRecord = this.waterfallMap.get(requestId);
```
Comment (andrewvc) [inline src/plugins/network.ts:81]: Will this work if there is `> 1` redirect? It looks to me like the answer is no, because the waterfall map will have the `:redirect` suffix after that.

**Review by andrewvc — CHANGES_REQUESTED** [review]
Found a potential issue. Also, can we add a unit test around this logic?

File: src/plugins/network.ts (hunk 1 above)
Comment (vigneshshanmugam) [reply src/plugins/network.ts:81]: Good catch. It's fixed now, also added tests.

**Review by andrewvc — APPROVED** [review]
LGTM

**Comment by vigneshshanmugam** [comment]
Docker build issue is fixed by #179
